typography_spectrum: 0.31041050837827056
content_rating:
  adult: false
color:
  brandStrength: 0.5812019459771379
  lightness: 0.6900768768933075
  saturation: 0.9588952844939425
  rhythmicContrast: 0.8124109686687958
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
github: true
layout_spectrum: 0.9800094052860605
analytics:
  google: UA-118310837-1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d64bd6c-9f9a-4028-81b3-fa14958209ec.png
name: Green Day / Zdrava Hrana
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: O nama
    id: 0b4c415d-5acd-41aa-9dbc-b4fb3774791a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3bba981-5a12-4850-b748-6da7069d820a.png
title: Green Day / Zdrava hrana
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/40e77bc1-9a74-461e-b0bc-17a25a1ef887.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/40e77bc1-9a74-461e-b0bc-17a25a1ef887.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Bez glutena, bez šećera, bez rafiniranog ulja i margarina,  bez konzervansa i
  aditiva. 
purpose:
  - type: contact
    url: 'tel:+38763424246'
    label: Call +38763424246
