layout_spectrum: 0.9800094052860605
typography_spectrum: 0.31041050837827056
color:
  brandStrength: 0.5812019459771379
  lightness: 0.6900768768933075
  saturation: 0.9588952844939425
  rhythmicContrast: 0.8124109686687958
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
name: Green Day / Zdrava Hrana
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
title: Green Day / Zdrava hrana
content: []
description: >-
  Bez glutena, bez šećera, bez rafiniranog ulja i margarina,  bez konzervansa i
  aditiva. 
purpose:
  - type: contact
    url: 'tel:+38763424246'
    label: Call +38763424246
  - type: internal
    label: O nama
    item: 0b4c415d-5acd-41aa-9dbc-b4fb3774791a
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/8d64bd6c-9f9a-4028-81b3-fa14958209ec.png
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b3bba981-5a12-4850-b748-6da7069d820a.png
github: true
content_rating:
  adult: false
